SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

ALTER TABLE `dehaantj_dsbarchief`.`documenten` CHANGE COLUMN `locatie_hc` `locatie_hc` INT(10) UNSIGNED NULL DEFAULT NULL COMMENT ' /* comment truncated */ /*locatie als in map id*/'  , ADD COLUMN `categorie` INT(10) UNSIGNED NULL DEFAULT NULL  AFTER `locatie_hc` ;

ALTER TABLE `dehaantj_dsbarchief`.`mappen` CHANGE COLUMN `map_id` `map_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT  ;

CREATE  TABLE IF NOT EXISTS `dehaantj_dsbarchief`.`categorieen` (
  `categorie_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT ,
  `naam` VARCHAR(45) NOT NULL ,
  `omschrijving` TEXT NULL DEFAULT NULL ,
  PRIMARY KEY (`categorie_id`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
