<?php

define('STD_WEGING_LID', 10);
define('STD_WEGING_EXTERNE_ORDE', 0);
define('STD_WEGING_BESTUUR', 0);
define('STD_WEGING_COMMISSIE', 0);

define('DSB_CREDIT_NUMMER_DEBITEUREN', 10001);
define('DSB_CREDIT_NUMMER_REGULIER',   10002);
define('DSB_DEBIT_NUMMER_DEBITEUREN',  20001);
define('DSB_DEBIT_NUMMER_REGULIER',    20002);

define('NOBEL_CREDIT_NUMMER_LOPENDE_REKENING', 10003);
define('NOBEL_CREDIT_NUMMER_SPAARREKENING', 10004);
define('NOBEL_DEBIT_NUMMER_LOPENDE_REKENING', 20003);
define('NOBEL_DEBIT_NUMMER_SPAARREKENING', 20004);

define('GB_BARBON_NUMMER', 30100);
define('GB_CONTRIBUTIE_NUMMER', 40100);
define('GB_SPAARPLAN_NUMMER', 30800);

define('CONTRIBUTIE_LID', 15);
define('CONTRIBUTIE_EXTERNE_ORDE', 5);
define('CONTRIBUTIE_BESTUUR', 10);

define('REKENING_NUMMER_LOPEND', 454972369);
define('REKENING_NUMMER_SPAAR', 454983271);

define('DATABASE_CURRENCY_PRECISION', 0.0001);

define('SPAARPLAN_MAANDELIJKS', 20.10);

?>